name: Latest blog post workflow
on:
 schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '* * * * *' # Run once a day instead of every hour
   
jobs:
  fetch-latest-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest blog post
        run: |
          retries=5
          delay=15
          for i in $(seq 1 $retries); do
            response=$(curl -s -o /dev/null -w "%{http_code}" https://maximilianocontieri.com/rss.xml)
            if [ $response -eq 200 ]; then
              echo "Fetched successfully"
              exit 0
            elif [ $response -eq 429 ]; then
              echo "Rate limited, retrying in $delay seconds..."
              sleep $delay
              delay=$((delay * 2))
            else
              echo "Failed with status code $response"
              exit 1
            fi
          done
          echo "Exceeded maximum retries"
          exit 1
